# Generated by Django 5.0 on 2025-11-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('needs', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='响应描述')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='介绍图片')),
                ('videos', models.JSONField(blank=True, default=list, verbose_name='介绍视频')),
                ('status', models.IntegerField(choices=[(0, '待接受'), (1, '已同意'), (2, '已拒绝'), (3, '已取消')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='needs.need', verbose_name='响应的需求')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_responses', to=settings.AUTH_USER_MODEL, verbose_name='响应用户')),
            ],
            options={
                'verbose_name': '服务响应',
                'verbose_name_plural': '服务响应',
                'db_table': 'responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcceptedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_date', models.DateField(verbose_name='接受日期')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_matches', to='needs.need', verbose_name='需求')),
                ('need_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_matches', to=settings.AUTH_USER_MODEL, verbose_name='需求发布者')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', verbose_name='地域')),
                ('response_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_matches', to=settings.AUTH_USER_MODEL, verbose_name='响应者')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_match', to='responses.response', verbose_name='响应')),
            ],
            options={
                'verbose_name': '响应成功明细',
                'verbose_name_plural': '响应成功明细',
                'db_table': 'accepted_matches',
            },
        ),
    ]
