# Generated by Django 5.0 on 2025-11-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=6, verbose_name='月份（YYYYMM）')),
                ('region_name', models.CharField(blank=True, max_length=200, verbose_name='地域名称')),
                ('service_type', models.CharField(max_length=50, verbose_name='服务类型')),
                ('total_needs', models.IntegerField(default=0, verbose_name='月累计发布需求数')),
                ('total_accepted', models.IntegerField(default=0, verbose_name='月累计响应成功数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', verbose_name='地域')),
            ],
            options={
                'verbose_name': '月度统计',
                'verbose_name_plural': '月度统计',
                'db_table': 'monthly_statistics',
                'unique_together': {('month', 'region', 'service_type')},
            },
        ),
    ]
