# Generated by Django 5.0 on 2025-11-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地域名称（区/县）')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='所属地市')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='所属省份')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='完整名称（省-市-区）')),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域',
                'db_table': 'regions',
            },
        ),
    ]
