# Generated by Django 5.0 on 2025-11-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('管道维修', '管道维修'), ('助老服务', '助老服务'), ('保洁服务', '保洁服务'), ('就诊服务', '就诊服务'), ('营养餐服务', '营养餐服务'), ('定期接送服务', '定期接送服务'), ('其他', '其他')], max_length=50, verbose_name='服务类型')),
                ('title', models.CharField(max_length=200, verbose_name='需求主题')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片路径')),
                ('videos', models.JSONField(blank=True, default=list, verbose_name='视频路径')),
                ('status', models.IntegerField(choices=[(0, '已发布'), (-1, '已取消')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to='regions.region', verbose_name='地域')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL, verbose_name='发布用户')),
            ],
            options={
                'verbose_name': '服务需求',
                'verbose_name_plural': '服务需求',
                'db_table': 'needs',
                'ordering': ['-created_at'],
            },
        ),
    ]
